import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Provider from "./provider";

const neon = localFont({
  src: './fonts/Neoneon-3zaD6.otf',
  variable: "--font-neon",
})

const kidding = localFont({
  src: './fonts/JustKidding-PPOd.ttf',
  variable: "--font-kidding",
})

const blocked = localFont({
  src: './fonts/BlockedOff-n4OR.ttf',
  variable: "--font-blocked",
})

const adventure = localFont({
  src: './fonts/AdventureSubtitlesBoldItalic-2Gao.ttf',
  variable: "--font-adventure",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neon.variable} ${adventure.variable} ${blocked.variable} ${kidding.variable} antialiased`}
      >
        <Provider>
          {children}
          <Toaster position="bottom-right" />
        </Provider>
      </body>
    </html>
  );
}
